export const SAVE_LOCAL_CONTACTS_IN_STORE = "SAVE_LOCAL_CONTACTS_IN_STORE";
export const SAVE_USER_INFO_IN_STORE = "SAVE_USER_INFO_IN_STORE";
export const LOAD_CONTACTS_FROM_FIREBASE_SUCCESS = "LOAD_CONTACTS_FROM_FIREBASE_SUCCESS";
export const LOAD_CONTACTS_FROM_FIREBASE_FAILED = "LOAD_CONTACTS_FROM_FIREBASE_FAILED"