export const SENT_MESSAGE_SENDING = "SENT_MESSAGE_SENDING";
export const SENT_MESSAGE_SUCCESS = "SENT_MESSAGE_SUCCESS";
export const SENT_MESSAGE_UPDATE = "SENT_MESSAGE_UPDATE";
export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS';
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR';
export const SAVE_MESSAGES_IN_STORE = 'SAVE_MESSAGES_IN_STORE';